name: Discomc
version: ${project.version}
main: com.github.jenya705.Discomc
api-version: 1.16
authors: [ Jenya705 ]
description: Strong Bridge between discord and minecraft
website: https://github.com/Jenya705/Discomc
